blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/lioarce01/agentic-context-toolkit/discussions/new
    about: Start a new discussion for general questions or support.
