name: Docs

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "README.md"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build documentation
        run: |
          source .venv/bin/activate
          python -m sphinx docs docs/_build
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build

